"""happy because it works

Revision ID: 56806360774f
Revises: bcc87e11a390
Create Date: 2024-12-05 00:41:48.255000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56806360774f"
down_revision: Union[str, None] = "bcc87e11a390"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_frames_test_data", table_name="frames")
    op.drop_column("frames", "test_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "frames",
        sa.Column("test_data", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.create_index("ix_frames_test_data", "frames", ["test_data"], unique=False)
    # ### end Alembic commands ###
