"""adding test column to see if it works

Revision ID: bcc87e11a390
Revises: 4c12f1a3f522
Create Date: 2024-12-05 00:40:39.482522

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bcc87e11a390"
down_revision: Union[str, None] = "4c12f1a3f522"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("frames", sa.Column("test_data", sa.Boolean(), nullable=True))
    op.create_index(op.f("ix_frames_test_data"), "frames", ["test_data"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_frames_test_data"), table_name="frames")
    op.drop_column("frames", "test_data")
    # ### end Alembic commands ###
